# foursquare api credientials
CLIENT_ID = 'OOABRTLTA4Y1AB1B3QE25PZSYQXA2QW44DBQ0EKHD0PWXAHP'
CLIENT_SECRET_ID = 'V1GZ3HPDHFGP1LSI21KOGXTW2JV0HFJHCSBQLDERT03ODXWF'
CALLBACK_URL = 'http://mymoneymomma.heroku.com/users/foursquare_callback'